apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-pipeline-run-
spec:
  pipelineRef:
    name: nodejs-pipeline
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/jinchihe/jinchi-he-express
    - name: image-repo
      value: quay.io/hejinchi_ibm/jinchi-he-express
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

