apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: jinchi-he-express
  app.kubernetes.io/instance: jinchi-he-express-instance
  app.kubernetes.io/name: jinchi-he-express
